CREATE OR REPLACE FUNCTION precioProducto (w_NOMBRE CATALOGO.NOMBRE%TYPE)
RETURN NUMBER IS w_PRECIO CATALOGO.PRECIO%TYPE;
BEGIN
SELECT PRECIO INTO w_PRECIO FROM CATALOGO WHERE (NOMBRE=w_NOMBRE);
RETURN(w_PRECIO);
END;
/

CREATE OR REPLACE FUNCTION numVentas (w_IDCATALOGO CATALOGO.IDCATALOGO%TYPE)
RETURN NUMBER IS w_cantidad  DETALLEVENTA.CANTIDAD%TYPE;
BEGIN
SELECT sum(CANTIDAD)into w_cantidad FROM DETALLEVENTA WHERE (IDCATALOGO=w_IDCATALOGO);
RETURN (W_CANTIDAD);
END;
/

CREATE OR REPLACE FUNCTION correoEmpleados (w_IDEMPLEADO EMPLEADOS.IDEMPLEADO%TYPE)
RETURN VARCHAR IS w_Correo EMPLEADOS.CORREO%TYPE;
BEGIN
SELECT correo into w_correo from empleados where (IDEMPLEADO=w_IDEMPLEADO);
RETURN(w_CORREO);
END;
/

CREATE OR REPLACE FUNCTION correoClientes (W_IDCLIENTE CLIENTES.IDCLIENTE%TYPE)
RETURN VARCHAR IS W_CORREO CLIENTES.CORREO%TYPE;
BEGIN
SELECT (CORREO) INTO W_CORREO FROM CLIENTES WHERE (IDCLIENTE= W_IDCLIENTE);
RETURN (W_CORREO);
END;
/

CREATE OR REPLACE FUNCTION ASSERT_EQUALS (salida Boolean, salida_esperada Boolean) Return VARCHAR2 AS
BEGIN
  If(salida=salida_esperada) THEN
    RETURN 'EXITO';
  ELSE
    RETURN 'FRACASO';
  END IF;
END ASSERT_EQUALS;
/



