--RI01 y RI02

SELECT NOMBRE,DESCRIPCION,STOCK,PRECIO FROM CATALOGO;

--RI03

SELECT NOMBRE FROM CATALOGO WHERE (STOCK>STOCKMINIMO);
SELECT NOMBRE,PRECIO,TIPOCATALOGO FROM CATALOGO WHERE (TipoCatalogo='Servicio');
--RI04

SELECT FECHAINICIO,FECHAFIN, DESCUENTO,NOMBRE FROM OFERTAS LEFT JOIN CATALOGO on OFERTAS.IDCATALOGO=CATALOGO.IDCATALOGO;
--OFERTAS VIGENTES
SELECT FECHAINICIO,FECHAFIN, DESCUENTO,NOMBRE FROM OFERTAS LEFT JOIN CATALOGO on OFERTAS.IDCATALOGO=CATALOGO.IDCATALOGO 
WHERE ((SYSDATE < FECHAFIN OR FECHAFIN is null) AND SYSDATE>FECHAINICIO );



--RI05

SELECT CANTIDAD,PRECIOCOMPRA,NOMBRE FROM DETALLECOMPRA LEFT JOIN CATALOGO on DETALLECOMPRA.IDCATALOGO=CATALOGO.IDCATALOGO;

--RI06

SELECT NOMBRE, EDAD, TELEFONO, DIRECCION, CORREO FROM EMPLEADOS;

--RI07

SELECT NOMBRE, TELEFONO, DIRECCION, CORREO FROM CLIENTES;

--RI08

SELECT CANTIDAD,PRECIOVENTA,  FECHAVENTA, NOMBRE FROM DETALLEVENTA NATURAL JOIN VENTAS NATURAL JOIN CATALOGO;

--RI09

SELECT IDFACTURA,FECHAFACTURA FROM FACTURA;

--RN01

SELECT IDCLIENTE,NOMBRE,APELLIDOS FROM CLIENTES WHERE (TIPO='Universitario');

--RN02
SELECT NOMBRE FROM CATALOGO WHERE (STOCK<STOCKMINIMO);

--RN03

SELECT IDEMPLEADO, NOMBRE FROM EMPLEADOS WHERE(SYSDATE-FECHAINICIO > 365);
--Empleados que estan trabajando actualmente y se le puede subir el sueldo
SELECT IDEMPLEADO,NOMBRE FROM EMPLEADOS WHERE (SYSDATE-FECHAINICIO > 365 AND (FECHAFIN>SYSDATE OR FECHAFIN IS NULL));

--RF03

SELECT * FROM PROVEEDOR;
