CREATE OR REPLACE PACKAGE PRUEBAS_EMPLEADOS AS
PROCEDURE INICIALIZAR;
PROCEDURE INSERTAR(NOMBRE_PRUEBA VARCHAR2,W_DNI VARCHAR,W_NOMBRE VARCHAR,W_APELLIDOS VARCHAR,W_DIRECCIÓN VARCHAR,W_CORREO VARCHAR,W_SALARIO NUMBER,W_FECHAINICIO DATE,W_FECHAFIN DATE,W_EDAD NUMBER,W_TELEFONO VARCHAR,SALIDAESPERADA BOOLEAN);
PROCEDURE ACTUALIZAR(NOMBRE_PRUEBA VARCHAR2,W_IDEMPLEADO NUMBER,W_DNI VARCHAR,W_NOMBRE VARCHAR,W_APELLIDOS VARCHAR,W_DIRECCIÓN VARCHAR,W_CORREO VARCHAR,W_SALARIO NUMBER,W_FECHAINICIO DATE,W_FECHAFIN DATE,W_EDAD NUMBER,W_TELEFONO VARCHAR,SALIDAESPERADA BOOLEAN);
PROCEDURE ELIMINAR(NOMBRE_PRUEBA VARCHAR2,W_IDEMPLEADO NUMBER,SALIDAESPERADA BOOLEAN);
END PRUEBAS_EMPLEADOS;
/
CREATE OR REPLACE PACKAGE BODY PRUEBAS_EMPLEADOS AS

PROCEDURE INICIALIZAR AS 
BEGIN 
 DELETE FROM EMPLEADOS;
 COMMIT WORK;
END INICIALIZAR;


 Procedure INSERTAR(NOMBRE_PRUEBA VARCHAR2,W_DNI VARCHAR,W_NOMBRE VARCHAR,W_APELLIDOS VARCHAR,W_DIRECCIÓN VARCHAR,W_CORREO VARCHAR,W_SALARIO NUMBER,W_FECHAINICIO DATE,W_FECHAFIN DATE,W_EDAD NUMBER,W_TELEFONO VARCHAR,SALIDAESPERADA BOOLEAN) AS
SALIDA BOOLEAN:= TRUE;
EMPLEADO EMPLEADOS%ROWTYPE;
W_IDEMPLEADO NUMBER;
BEGIN

INSERT INTO EMPLEADOS VALUES(SEC_EMPLEADOS.NEXTVAL,W_DNI,W_NOMBRE ,W_APELLIDOS ,W_DIRECCIÓN,W_CORREO,W_SALARIO,W_FECHAINICIO ,W_FECHAFIN ,W_EDAD ,W_TELEFONO );
W_IDEMPLEADO :=SEC_EMPLEADOS.CURRVAL;
SELECT * INTO EMPLEADO FROM EMPLEADOS WHERE IDEMPLEADO=W_IDEMPLEADO;
IF(EMPLEADO.DNI<>W_DNI OR EMPLEADO.NOMBRE<>W_NOMBRE OR EMPLEADO.APELLIDOS<>W_APELLIDOS OR EMPLEADO.DIRECCIÓN<>W_DIRECCIÓN OR EMPLEADO.CORREO<>W_CORREO OR EMPLEADO.SALARIO<>W_SALARIO OR EMPLEADO.FECHAINICIO<>W_FECHAINICIO OR EMPLEADO.FECHAFIN<>W_FECHAFIN OR EMPLEADO.EDAD<>W_EDAD OR EMPLEADO.TELEFONO<>W_TELEFONO)THEN
SALIDA :=FALSE;
END IF;
COMMIT WORK;
DBMS_OUTPUT.PUT_LINE(NOMBRE_PRUEBA || ':' || ASSERT_EQUALS(SALIDA, SALIDAESPERADA));

EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(NOMBRE_PRUEBA || ':' || ASSERT_EQUALS(FALSE, SALIDAESPERADA));
ROLLBACK;
END INSERTAR;





 Procedure ACTUALIZAR(NOMBRE_PRUEBA VARCHAR2,W_IDEMPLEADO NUMBER,W_DNI VARCHAR,W_NOMBRE VARCHAR,W_APELLIDOS VARCHAR,W_DIRECCIÓN VARCHAR,W_CORREO VARCHAR,W_SALARIO NUMBER,W_FECHAINICIO DATE,W_FECHAFIN DATE,W_EDAD NUMBER,W_TELEFONO VARCHAR,SALIDAESPERADA BOOLEAN) AS
SALIDA BOOLEAN:= TRUE;
EMPLEADO EMPLEADOS%ROWTYPE;

BEGIN

UPDATE EMPLEADOS SET DNI=W_DNI,NOMBRE=W_NOMBRE,APELLIDOS=W_APELLIDOS,DIRECCIÓN=W_DIRECCIÓN,CORREO=W_CORREO,SALARIO=W_SALARIO,FECHAINICIO=W_FECHAINICIO,FECHAFIN=W_FECHAFIN,EDAD=W_EDAD,TELEFONO=W_TELEFONO WHERE IDEMPLEADO=W_IDEMPLEADO;

SELECT * INTO EMPLEADO FROM EMPLEADOS WHERE IDEMPLEADO=W_IDEMPLEADO;
IF(EMPLEADO.DNI<>W_DNI OR EMPLEADO.NOMBRE<>W_NOMBRE OR EMPLEADO.APELLIDOS<>W_APELLIDOS OR EMPLEADO.DIRECCIÓN<>W_DIRECCIÓN OR EMPLEADO.CORREO<>W_CORREO OR EMPLEADO.SALARIO<>W_SALARIO OR EMPLEADO.FECHAINICIO<>W_FECHAINICIO OR EMPLEADO.FECHAFIN<>W_FECHAFIN OR EMPLEADO.EDAD<>W_EDAD OR EMPLEADO.TELEFONO<>W_TELEFONO)THEN
SALIDA :=FALSE;
END IF;
COMMIT WORK;
DBMS_OUTPUT.PUT_LINE(NOMBRE_PRUEBA || '1:' || ASSERT_EQUALS(SALIDA, SALIDAESPERADA));

EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(NOMBRE_PRUEBA || '2:' || ASSERT_EQUALS(FALSE, SALIDAESPERADA));
ROLLBACK;
END ACTUALIZAR;


 Procedure ELIMINAR(NOMBRE_PRUEBA VARCHAR2,W_IDEMPLEADO NUMBER,SALIDAESPERADA BOOLEAN) AS
SALIDA BOOLEAN:= TRUE;
N_EMPLEADO INTEGER;

BEGIN
DELETE FROM EMPLEADOS  WHERE IDEMPLEADO=W_IDEMPLEADO;

SELECT COUNT (*) INTO N_EMPLEADO FROM EMPLEADOS WHERE IDEMPLEADO=W_IDEMPLEADO;
IF(N_EMPLEADO<>0)THEN
SALIDA :=FALSE;
END IF;
COMMIT WORK;
DBMS_OUTPUT.PUT_LINE(NOMBRE_PRUEBA || ':' || ASSERT_EQUALS(SALIDA, SALIDAESPERADA));

EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(NOMBRE_PRUEBA || ':' || ASSERT_EQUALS(FALSE, SALIDAESPERADA));
ROLLBACK;
END ELIMINAR;

END PRUEBAS_EMPLEADOS;
/
