CREATE OR REPLACE PROCEDURE INSERTAR_EMPLEADOS(
DNI IN EMPLEADOS.DNI%TYPE, NOMBRE IN EMPLEADOS.NOMBRE%TYPE, APELLIDOS IN EMPLEADOS.APELLIDOS%TYPE, DIRECCION IN EMPLEADOS.DIRECCION%TYPE,
CORREO IN EMPLEADOS.CORREO%TYPE, FECHAINICIO IN EMPLEADOS.FECHAINICIO%TYPE, FECHAFIN IN EMPLEADOS.FECHAFIN%TYPE,
EDAD IN EMPLEADOS.EDAD%TYPE ,TELEFONO IN EMPLEADOS.TELEFONO%TYPE, USUARIO IN EMPLEADOS.USUARIO%TYPE, PASS IN EMPLEADOS.PASS%TYPE)
IS BEGIN INSERT INTO
EMPLEADOS(DNI,NOMBRE,APELLIDOS,DIRECCION,CORREO,SALARIO,FECHAINICIO,FECHAFIN,EDAD,TELEFONO,USUARIO,PASS)
VALUES(DNI,NOMBRE,APELLIDOS,DIRECCION,CORREO,1000,FECHAINICIO,FECHAFIN,EDAD,TELEFONO,USUARIO,PASS);
COMMIT WORK;
END INSERTAR_EMPLEADOS;
/
CREATE OR REPLACE PROCEDURE DESPEDIR_EMPLEADO(IDEMP IN EMPLEADOS.IDEMPLEADO%TYPE)
IS BEGIN UPDATE EMPLEADOS SET FECHAFIN=SYSDATE, PASS=NULL WHERE IDEMP=IDEMPLEADO;
COMMIT WORK;
END DESPEDIR_EMPLEADO;
/
CREATE OR REPLACE PROCEDURE ELIMINAR_EMPLEADOS(
IDEMP IN EMPLEADOS.IDEMPLEADO%TYPE) IS BEGIN DELETE FROM EMPLEADOS WHERE IDEMP=IDEMPLEADO;
COMMIT WORK;
END ELIMINAR_EMPLEADOS;
/
CREATE OR REPLACE PROCEDURE ACTUALIZA_EMPLEADO(IDEMP IN EMPLEADOS.IDEMPLEADO%TYPE, 
	EMAIL IN EMPLEADOS.CORREO%TYPE, SUELDO IN EMPLEADOS.SALARIO%TYPE) IS BEGIN
	UPDATE EMPLEADOS SET CORREO=EMAIL, SALARIO=SUELDO WHERE IDEMP=IDEMPLEADO;
	COMMIT WORK;
	END ACTUALIZA_EMPLEADO;
	/

CREATE OR REPLACE PROCEDURE INSERTAR_CATALOGOS(
NOMBRE IN CATALOGO.NOMBRE%TYPE, DESCRIPCION IN CATALOGO.DESCRIPCION%TYPE, PRECIO IN CATALOGO.PRECIO%TYPE, 
IVA IN CATALOGO.IVA%TYPE, STOCK IN CATALOGO.STOCK%TYPE, STOCKMINIMO IN CATALOGO.STOCKMINIMO%TYPE,
TIPOPRODUCTO IN CATALOGO.TIPOPRODUCTO%TYPE, TIPOCATALOGO IN CATALOGO.TIPOCATALOGO%TYPE)
IS BEGIN INSERT INTO
CATALOGO(NOMBRE,DESCRIPCION,PRECIO,IVA,STOCK,STOCKMINIMO,TIPOPRODUCTO,TIPOCATALOGO)
VALUES(NOMBRE,DESCRIPCION,PRECIO,IVA,STOCK,STOCKMINIMO,TIPOPRODUCTO,TIPOCATALOGO);
COMMIT WORK;
END INSERTAR_CATALOGOS;
/

CREATE OR REPLACE PROCEDURE ELIMINAR_CATALOGOS(
IDCAT IN CATALOGO.IDCATALOGO%TYPE) IS BEGIN DELETE FROM CATALOGO WHERE IDCAT=IDCATALOGO;
COMMIT WORK;
END ELIMINAR_CATALOGOS;
/

CREATE OR REPLACE PROCEDURE ACTUALIZA_CATALOGO(IDCAT IN CATALOGO.IDCATALOGO%TYPE, 
	DINERO IN CATALOGO.PRECIO%TYPE) IS BEGIN
	UPDATE CATALOGO SET PRECIO=DINERO WHERE IDCAT=IDCATALOGO;
	COMMIT WORK;
	END ACTUALIZA_CATALOGO;
	/




  CREATE OR REPLACE PROCEDURE INSERTAR_CLIENTES(
DNI IN CLIENTES.DNI%TYPE, NOMBRE IN CLIENTES.NOMBRE%TYPE, APELLIDOS IN CLIENTES.APELLIDOS%TYPE, 
CORREO IN CLIENTES.CORREO%TYPE,DIRECCION IN CLIENTES.DIRECCION%TYPE,
TELEFONO IN CLIENTES.TELEFONO%TYPE, TIPO IN CLIENTES.TIPO%TYPE, USUARIO IN CLIENTES.USUARIO%TYPE, PASS IN CLIENTES.PASS%TYPE )
IS BEGIN INSERT INTO
CLIENTES(DNI,NOMBRE,APELLIDOS,CORREO,DIRECCION,TELEFONO,TIPO,USUARIO,PASS)
VALUES(DNI,NOMBRE,APELLIDOS,CORREO,DIRECCION,TELEFONO,TIPO,USUARIO,PASS);
COMMIT WORK;
END INSERTAR_CLIENTES;
/

CREATE OR REPLACE PROCEDURE ACTUALIZA_CLIENTE(IDCLIEN IN CLIENTES.IDCLIENTE%TYPE,NIF IN CLIENTES.DNI%TYPE, NAME IN CLIENTES.NOMBRE%TYPE, n_APELLIDOS IN CLIENTES.APELLIDOS%TYPE, 
EMAIL IN CLIENTES.CORREO%TYPE,DIR IN CLIENTES.DIRECCION%TYPE,
TLF IN CLIENTES.TELEFONO%TYPE, UNIV IN CLIENTES.TIPO%TYPE, NICK IN CLIENTES.USUARIO%TYPE, CONTRA IN CLIENTES.PASS%TYPE) IS BEGIN
UPDATE CLIENTES SET DNI=NIF, NOMBRE=NAME,APELLIDOS= n_APELLIDOS, CORREO=EMAIL, DIRECCION=DIR, TELEFONO=TLF,TIPO=UNIV,USUARIO=NICK,PASS=CONTRA 
WHERE (IDCLIEN=IDCLIENTE);
COMMIT WORK;
END ACTUALIZA_CLIENTE;
/

CREATE OR REPLACE PROCEDURE INSERTAR_COMPRAS(
FECHACOMPRA IN COMPRAS.FECHACOMPRA%TYPE, IDPROVEEDOR IN COMPRAS.IDPROVEEDOR%TYPE)
IS BEGIN INSERT INTO
COMPRAS(FECHACOMPRA,TOTAL,IDPROVEEDOR)
VALUES(FECHACOMPRA,0,IDPROVEEDOR);
COMMIT WORK;
END INSERTAR_COMPRAS;

/
CREATE OR REPLACE PROCEDURE insertar_Proveedor(
w_CIF IN PROVEEDOR.CIF%TYPE, 
w_empresa IN PROVEEDOR.EMPRESA%TYPE,
w_direccion IN PROVEEDOR.DIRECCION%TYPE)IS
BEGIN
INSERT INTO PROVEEDOR(CIF,EMPRESA,DIRECCION) VALUES(w_CIF,w_empresa,w_direccion);
COMMIT WORK;

END insertar_Proveedor;
/


CREATE OR REPLACE PROCEDURE INSERTAR_VENTAS(
FECHAVENTA IN VENTAS.FECHAVENTA%TYPE,
IDEMPLEADO IN VENTAS.IDEMPLEADO%TYPE,
IDCLIENTE IN VENTAS.IDCLIENTE%TYPE)IS


BEGIN
INSERT INTO VENTAS(FECHAVENTA,TOTAL,IDEMPLEADO,IDCLIENTE) VALUES(FECHAVENTA,0,IDEMPLEADO,IDCLIENTE);

COMMIT WORK;
END INSERTAR_VENTAS;

/





CREATE OR REPLACE PROCEDURE INSERTAR_OFERTAS(
FECHAINICIO IN OFERTAS.FECHAINICIO%TYPE,
FECHAFIN IN OFERTAS.FECHAFIN%TYPE,
DESCUENTO IN OFERTAS.DESCUENTO%TYPE,
IDCATALOGO IN OFERTAS.IDCATALOGO%TYPE)IS
BEGIN
INSERT INTO OFERTAS(FECHAINICIO,FECHAFIN,DESCUENTO,IDCATALOGO) VALUES (FECHAINICIO,FECHAFIN,DESCUENTO,IDCATALOGO);
COMMIT WORK;
END INSERTAR_OFERTAS;
/

CREATE OR REPLACE PROCEDURE INSERTAR_FACTURAS(
FECHAFACTURA IN FACTURA.FECHAFACTURA%TYPE,
IDVENTA IN FACTURA.IDVENTA%TYPE)IS
BEGIN
INSERT INTO FACTURA(FECHAFACTURA,IDVENTA) VALUES(FECHAFACTURA,IDVENTA);
COMMIT WORK;
END INSERTAR_FACTURAS;
/


CREATE or replace PROCEDURE INSERTAR_DETALLECOMPRA(
W_CANTIDAD IN DETALLECOMPRA.CANTIDAD%TYPE, 
W_PRECIOCOMPRA IN DETALLECOMPRA.PRECIOCOMPRA %TYPE,
W_IVA IN DETALLECOMPRA.IVA%TYPE,
W_IDCOMPRAS IN DETALLECOMPRA.IDCOMPRAS%TYPE,
W_IDCATALOGO IN DETALLECOMPRA.IDCATALOGO%TYPE)IS
W_TOTAL COMPRAS.TOTAL%TYPE;
w_STOCK CATALOGO.STOCK%TYPE;
BEGIN 
   INSERT INTO DETALLECOMPRA(CANTIDAD ,PRECIOCOMPRA ,IVA,IDCOMPRAS,IDCATALOGO) VALUES(W_CANTIDAD ,W_PRECIOCOMPRA ,W_IVA,W_IDCOMPRAS,W_IDCATALOGO);
   SELECT TOTAL INTO W_TOTAL FROM COMPRAS WHERE (IDCOMPRAS= W_IDCOMPRAS);
  UPDATE COMPRAS SET TOTAL= W_TOTAL+W_CANTIDAD*W_PRECIOCOMPRA*(1+W_IVA) WHERE IDCOMPRAS= W_IDCOMPRAS;
   SELECT STOCK INTO w_STOCK FROM CATALOGO WHERE (IDCATALOGO= w_IDCATALOGO);
   UPDATE CATALOGO SET STOCK= w_CANTIDAD+W_STOCK WHERE IDCATALOGO=w_IDCATALOGO;
   
   COMMIT WORK;
END INSERTAR_DETALLECOMPRA;
/

create or replace PROCEDURE INSERTAR_DETALLEVENTA(
W_CANTIDAD IN DETALLEVENTA.CANTIDAD%TYPE,
W_PRECIOVENTA IN DETALLEVENTA.PRECIOVENTA%TYPE, 
W_IVA IN DETALLEVENTA.IVA%TYPE,
W_IDVENTAS IN DETALLEVENTA.IDVENTAS%TYPE, 
W_IDCATALOGO IN DETALLEVENTA.IDCATALOGO%TYPE)IS
W_TOTAL VENTAS.TOTAL%TYPE;
w_STOCK CATALOGO.STOCK%TYPE;
w_IDCLIENTE CLIENTES.IDCLIENTE%TYPE;
w_TIPO CLIENTES.TIPO%TYPE;
w_VENTA VENTAS%ROWTYPE;
w_CATALOGO CATALOGO%ROWTYPE;


BEGIN 
    INSERT INTO DETALLEVENTA(CANTIDAD ,PRECIOVENTA ,IVA, IDVENTAS,IDCATALOGO) VALUES(W_CANTIDAD ,W_PRECIOVENTA ,W_IVA, W_IDVENTAS, W_IDCATALOGO);
   SELECT TOTAL INTO w_TOTAL FROM VENTAS WHERE IDVENTAS=w_IDVENTAS;
    --Reducimos el precio por universitario
     SELECT * INTO w_VENTA FROM VENTAS WHERE (IDVENTAS=w_IDVENTAS);
    IF (w_VENTA.IDCLIENTE is not null)THEN
    SELECT IDCLIENTE INTO w_IDCLIENTE FROM VENTAS WHERE IDVENTAS=w_IDVENTAS;
    SELECT TIPO INTO w_TIPO FROM CLIENTES WHERE IDCLIENTE=w_IDCLIENTE;
    IF(w_TIPO='Universitario')THEN
    UPDATE VENTAS SET TOTAL= W_TOTAL+W_CANTIDAD*W_PRECIOVENTA*(1+W_IVA)*'0,9' WHERE IDVENTAS= W_IDVENTAS;
    ELSE
     UPDATE VENTAS SET TOTAL= W_TOTAL+W_CANTIDAD*W_PRECIOVENTA*(1+W_IVA) WHERE IDVENTAS= W_IDVENTAS;
     END IF;
    
    ELSE
    UPDATE VENTAS SET TOTAL= W_TOTAL+W_CANTIDAD*W_PRECIOVENTA*(1+W_IVA) WHERE IDVENTAS= W_IDVENTAS;
    END IF;
 
  
    SELECT * INTO w_CATALOGO FROM CATALOGO WHERE (IDCATALOGO=W_IDCATALOGO);
    IF(w_CATALOGO.TIPOCATALOGO='PRODUCTO')THEN
    --Reducimos el Stock
    SELECT STOCK INTO w_STOCK FROM CATALOGO WHERE (IDCATALOGO= w_IDCATALOGO);
   UPDATE CATALOGO SET STOCK= W_STOCK-W_CANTIDAD WHERE IDCATALOGO=w_IDCATALOGO;
   END IF;
    COMMIT WORK;
END INSERTAR_DETALLEVENTA;
/
CREATE OR REPLACE PROCEDURE ELIMINAR_DETALLEVENTA(
w_IDDETALLEVENTA IN DETALLEVENTA.IDDETALLEVENTA%TYPE) IS 
W_TOTAL VENTAS.TOTAL%TYPE;
w_STOCK CATALOGO.STOCK%TYPE;
w_IDCLIENTE CLIENTES.IDCLIENTE%TYPE;
w_TIPO CLIENTES.TIPO%TYPE;
w_VENTA VENTAS%ROWTYPE;
w_CATALOGO CATALOGO%ROWTYPE;
w_IDVENTAS VENTAS.IDVENTAS%TYPE;
w_IDCATALOGO CATALOGO.IDCATALOGO%TYPE;
w_IVA DETALLEVENTA.IVA%TYPE;
w_CANTIDAD DETALLEVENTA.CANTIDAD%TYPE;
w_PRECIOVENTA DETALLEVENTA.PRECIOVENTA%TYPE;
BEGIN 
  SELECT IDVENTAS INTO w_IDVENTAS FROM DETALLEVENTA WHERE (IDDETALLEVENTA=w_IDDETALLEVENTA);
  SELECT IDCATALOGO INTO w_IDCATALOGO FROM DETALLEVENTA WHERE (IDDETALLEVENTA=w_IDDETALLEVENTA);
  SELECT IVA INTO w_IVA FROM DETALLEVENTA WHERE (IDDETALLEVENTA=w_IDDETALLEVENTA);
  SELECT CANTIDAD INTO w_CANTIDAD FROM DETALLEVENTA WHERE (IDDETALLEVENTA=w_IDDETALLEVENTA);
  SELECT PRECIOVENTA INTO w_PRECIOVENTA FROM DETALLEVENTA WHERE (IDDETALLEVENTA=w_IDDETALLEVENTA);
 SELECT TOTAL INTO w_TOTAL FROM VENTAS WHERE IDVENTAS=w_IDVENTAS;
 SELECT * INTO w_VENTA FROM VENTAS WHERE (IDVENTAS=w_IDVENTAS);
 DELETE FROM DETALLEVENTA WHERE IDDETALLEVENTA=w_IDDETALLEVENTA;


    --Reducimos el precio por universitario

    IF (w_VENTA.IDCLIENTE is not null)THEN
    SELECT IDCLIENTE INTO w_IDCLIENTE FROM VENTAS WHERE IDVENTAS=w_IDVENTAS;
    SELECT TIPO INTO w_TIPO FROM CLIENTES WHERE IDCLIENTE=w_IDCLIENTE;
   
    IF(w_TIPO='Universitario')THEN
    UPDATE VENTAS SET TOTAL= W_TOTAL-W_CANTIDAD*W_PRECIOVENTA*(1+W_IVA)*'0,9' WHERE (IDVENTAS= W_IDVENTAS);
    ELSE
     UPDATE VENTAS SET TOTAL= W_TOTAL-W_CANTIDAD*W_PRECIOVENTA*(1+W_IVA) WHERE IDVENTAS= W_IDVENTAS;
     
     END IF;
    
   
   
    ELSE
    UPDATE VENTAS SET TOTAL= W_TOTAL-W_CANTIDAD*W_PRECIOVENTA*(1+W_IVA) WHERE IDVENTAS= W_IDVENTAS;
    END IF;
    
     SELECT * INTO w_CATALOGO FROM CATALOGO WHERE (IDCATALOGO=W_IDCATALOGO);
    IF(w_CATALOGO.TIPOCATALOGO='PRODUCTO')THEN
    --Reducimos el Stock
    SELECT STOCK INTO w_STOCK FROM CATALOGO WHERE (IDCATALOGO= w_IDCATALOGO);
   UPDATE CATALOGO SET STOCK= W_STOCK+W_CANTIDAD WHERE IDCATALOGO=w_IDCATALOGO;
   END IF;
   
    
    COMMIT WORK;



END ELIMINAR_DETALLEVENTA;
/



CREATE OR REPLACE PROCEDURE ELIMINAR_CLIENTES(
IDCLIEN IN CLIENTES.IDCLIENTE%TYPE) IS BEGIN DELETE FROM CLIENTES WHERE IDCLIEN=IDCLIENTE;
COMMIT WORK;
END ELIMINAR_CLIENTES;
/
CREATE OR REPLACE PROCEDURE ELIMINAR_COMPRAS(
IDCOMP IN COMPRAS.IDCOMPRAS%TYPE) IS BEGIN DELETE FROM COMPRAS WHERE IDCOMP=IDCOMPRAS;
COMMIT WORK;
END ELIMINAR_COMPRAS;
/
CREATE OR REPLACE PROCEDURE ELIMINAR_PROVEEDOR(
IDPROV IN PROVEEDOR.IDPROVEEDOR%TYPE) IS BEGIN DELETE FROM PROVEEDOR WHERE IDPROV=IDPROVEEDOR;
COMMIT WORK;
END ELIMINAR_PROVEEDOR;
/
CREATE OR REPLACE PROCEDURE ELIMINAR_VENTAS(
IDVENT IN VENTAS.IDVENTAS%TYPE) IS BEGIN DELETE FROM VENTAS WHERE IDVENT=IDVENTAS;
COMMIT WORK;
END ELIMINAR_VENTAS;
/
CREATE OR REPLACE PROCEDURE ELIMINAR_OFERTAS(
IDOFERTA IN OFERTAS.IDOFERTA%TYPE) IS BEGIN DELETE FROM OFERTAS WHERE OFERTAS.IDOFERTA=IDOFERTA;
COMMIT WORK;
END ELIMINAR_OFERTAS;
/
CREATE OR REPLACE PROCEDURE ELIMINAR_FACTURA(
IDFACTURA IN FACTURA.IDFACTURA%TYPE) IS BEGIN DELETE FROM FACTURA WHERE FACTURA.IDFACTURA=IDFACTURA;
COMMIT WORK;
END ELIMINAR_FACTURA;
/
create or replace PROCEDURE ELIMINAR_DETALLECOMPRA(
W_IDDETALLECOMPRA IN DETALLECOMPRA.IDDETALLECOMPRA%TYPE) IS 
W_CANTIDAD DETALLECOMPRA.CANTIDAD%TYPE;
W_PRECIO DETALLECOMPRA.PRECIOCOMPRA%TYPE;
W_IVA DETALLECOMPRA.IVA%TYPE;
W_TOTAL COMPRAS.TOTAL%TYPE;
W_IDCOMPRAS DETALLECOMPRA.IDCOMPRAS%TYPE;
W_STOCK CATALOGO.STOCK%TYPE;
W_IDCATALOGO DETALLECOMPRA.IDCATALOGO%TYPE;
BEGIN 

  SELECT CANTIDAD, PRECIOCOMPRA, IVA, IDCOMPRAS, IDCATALOGO INTO W_CANTIDAD,W_PRECIO, W_IVA, W_IDCOMPRAS, W_IDCATALOGO FROM DETALLECOMPRA WHERE (IDDETALLECOMPRA=W_IDDETALLECOMPRA);
  DELETE FROM DETALLECOMPRA WHERE IDDETALLECOMPRA=W_IDDETALLECOMPRA;
  SELECT TOTAL INTO W_TOTAL FROM COMPRAS WHERE (IDCOMPRAS= W_IDCOMPRAS);
  UPDATE COMPRAS SET TOTAL= W_TOTAL-W_CANTIDAD*W_PRECIO*(1+W_IVA) WHERE (IDCOMPRAS= W_IDCOMPRAS);
  IF (W_IDCATALOGO IS NOT NULL) THEN
      SELECT STOCK INTO W_STOCK FROM CATALOGO WHERE (IDCATALOGO=W_IDCATALOGO);
      UPDATE CATALOGO SET STOCK = W_STOCK-W_CANTIDAD WHERE IDCATALOGO=W_IDCATALOGO;
   END IF;
  COMMIT WORK;
END ELIMINAR_DETALLECOMPRA;
/
create or replace procedure ACTUALIZAR_DETALLEVENTA(N_IDDETALLEVENTA IN DETALLEVENTA.IDDETALLEVENTA%TYPE,
N_CANTIDAD DETALLEVENTA.CANTIDAD%TYPE,
N_PRECIO DETALLEVENTA.PRECIOVENTA%TYPE,
N_IVA DETALLEVENTA.IVA%TYPE,
N_IDCATALOGO DETALLEVENTA.IDCATALOGO%TYPE) IS

W_CANTIDAD DETALLEVENTA.CANTIDAD%TYPE;
W_PRECIO DETALLEVENTA.PRECIOVENTA%TYPE;
W_IVA DETALLEVENTA.IVA%TYPE;
W_TOTAL VENTAS.TOTAL%TYPE;
W_IDVENTAS DETALLEVENTA.IDVENTAS%TYPE;
W_STOCK CATALOGO.STOCK%TYPE;
n_STOCK CATALOGO.STOCK%TYPE;
W_IDCATALOGO DETALLEVENTA.IDCATALOGO%TYPE;
w_IDCLIENTE CLIENTES.IDCLIENTE%TYPE;
w_TIPO CLIENTES.TIPO%TYPE;

w_VENTA VENTAS%ROWTYPE;
w_CATALOGO CATALOGO%ROWTYPE;
n_CATALOGO CATALOGO%ROWTYPE;

BEGIN

SELECT CANTIDAD,PRECIOVENTA,IVA,IDVENTAS, IDCATALOGO INTO w_CANTIDAD, w_PRECIO, w_IVA, w_IDVENTAS, w_IDCATALOGO
FROM DETALLEVENTA WHERE (IDDETALLEVENTA=n_IDDETALLEVENTA);
SELECT * INTO w_VENTA FROM VENTAS WHERE (IDVENTAS=w_IDVENTAS);
SELECT TOTAL INTO w_TOTAL FROM VENTAS WHERE (IDVENTAS=w_IDVENTAS);
UPDATE DETALLEVENTA SET
CANTIDAD=n_CANTIDAD,
PRECIOVENTA=n_PRECIO,
IVA=n_IVA,
IDCATALOGO=n_IDCATALOGO WHERE (IDDETALLEVENTA=n_IDDETALLEVENTA);


 IF (w_VENTA.IDCLIENTE is not null)THEN
    SELECT IDCLIENTE INTO w_IDCLIENTE FROM VENTAS WHERE IDVENTAS=w_IDVENTAS;
    SELECT TIPO INTO w_TIPO FROM CLIENTES WHERE IDCLIENTE=w_IDCLIENTE;
   
    IF(w_TIPO='Universitario')THEN
    UPDATE VENTAS SET TOTAL= W_TOTAL+((n_CANTIDAD*n_PRECIO*(1+n_IVA))-(W_CANTIDAD*W_PRECIO*(1+W_IVA)*'0,9')) WHERE (IDVENTAS= W_IDVENTAS);
    ELSE
     UPDATE VENTAS SET TOTAL= W_TOTAL+((n_CANTIDAD*n_PRECIO*(1+n_IVA))-(W_CANTIDAD*W_PRECIO*(1+W_IVA))) WHERE IDVENTAS= W_IDVENTAS;
     
     END IF;
    
   
   
    ELSE
    UPDATE VENTAS SET TOTAL= W_TOTAL+((n_CANTIDAD*n_PRECIO*(1+n_IVA))-(W_CANTIDAD*W_PRECIO*(1+W_IVA))) WHERE IDVENTAS= W_IDVENTAS;
    END IF;
    
     SELECT * INTO w_CATALOGO FROM CATALOGO WHERE IDCATALOGO=w_IDCATALOGO;
    
   IF(w_CATALOGO.TIPOCATALOGO='PRODUCTO')THEN
    --Aumentamos el Stock
    SELECT STOCK INTO w_STOCK FROM CATALOGO WHERE (IDCATALOGO= w_IDCATALOGO);
   UPDATE CATALOGO SET STOCK= W_STOCK+W_CANTIDAD WHERE IDCATALOGO=w_IDCATALOGO;
   
   END IF;
   
   SELECT * INTO n_CATALOGO FROM CATALOGO WHERE IDCATALOGO=n_IDCATALOGO;
   
   IF(n_CATALOGO.TIPOCATALOGO='PRODUCTO')THEN
   SELECT STOCK INTO w_STOCK FROM CATALOGO WHERE IDCATALOGO=N_IDCATALOGO;
   UPDATE CATALOGO SET STOCK = N_STOCK-W_CANTIDAD WHERE IDCATALOGO=n_IDCATALOGO;
   
   END IF;
   
   
   
  
   COMMIT WORK;



END ACTUALIZAR_DETALLEVENTA;
/


create or replace PROCEDURE ACTUALIZAR_DETALLECOMPRA(
N_IDDETALLECOMPRA IN DETALLECOMPRA.IDDETALLECOMPRA%TYPE, 
N_CANTIDAD DETALLECOMPRA.CANTIDAD%TYPE,
N_PRECIO DETALLECOMPRA.PRECIOCOMPRA%TYPE,
N_IVA DETALLECOMPRA.IVA%TYPE,
N_IDCATALOGO DETALLECOMPRA.IDCATALOGO%TYPE) IS

W_CANTIDAD DETALLECOMPRA.CANTIDAD%TYPE;
W_PRECIO DETALLECOMPRA.PRECIOCOMPRA%TYPE;
W_IVA DETALLECOMPRA.IVA%TYPE;
W_TOTAL COMPRAS.TOTAL%TYPE;
W_IDCOMPRAS DETALLECOMPRA.IDCOMPRAS%TYPE;
W_STOCK CATALOGO.STOCK%TYPE;
W_IDCATALOGO DETALLECOMPRA.IDCATALOGO%TYPE;
BEGIN 

  SELECT CANTIDAD, PRECIOCOMPRA, IVA, IDCOMPRAS, IDCATALOGO INTO W_CANTIDAD,W_PRECIO, W_IVA, W_IDCOMPRAS, W_IDCATALOGO  FROM DETALLECOMPRA WHERE (IDDETALLECOMPRA=N_IDDETALLECOMPRA);
  UPDATE DETALLECOMPRA
    SET  CANTIDAD = N_CANTIDAD,
      PRECIOCOMPRA = N_PRECIO,
      IVA = N_IVA,
      IDCATALOGO = N_IDCATALOGO
    WHERE IDDETALLECOMPRA =N_IDDETALLECOMPRA;
 -- DBMS_OUTPUT.PUT_LINE('Despues: '||W_IDDETALLECOMPRA||' '||W_CANTIDAD||' '||W_PRECIO||' '||W_IVA);
  SELECT TOTAL INTO W_TOTAL FROM COMPRAS WHERE (IDCOMPRAS= W_IDCOMPRAS);
  W_TOTAL:= W_TOTAL+N_CANTIDAD*N_PRECIO*(1+N_IVA)-W_CANTIDAD*W_PRECIO*(1+W_IVA);
  UPDATE COMPRAS SET TOTAL = W_TOTAL WHERE (IDCOMPRAS= W_IDCOMPRAS);
  IF (W_IDCATALOGO IS NOT NULL) THEN
      SELECT STOCK INTO W_STOCK FROM CATALOGO WHERE (IDCATALOGO=W_IDCATALOGO);
      UPDATE CATALOGO SET STOCK = W_STOCK+N_CANTIDAD-W_CANTIDAD WHERE IDCATALOGO=W_IDCATALOGO;
   END IF;
  COMMIT WORK;
END ACTUALIZAR_DETALLECOMPRA;
/

create or replace FUNCTION ventaHoy (w_IDVENTAS VENTAS.IDVENTAS%TYPE, w_FECHA2 DATE)
RETURN VARCHAR IS

w_FECHA DATE;

BEGIN
SELECT DISTINCT FECHAVENTA INTO w_FECHA FROM VENTAS WHERE IDVENTAS=w_IDVENTAS;


IF(w_FECHA > w_FECHA2 ) THEN
RETURN 'true';
ELSE 
RETURN 'false';
END IF;


END;
/