EXECUTE INSERTAR_CLIENTES ('32094173L','Angel','Perez',null,'Triana','638075958','Universitario');
EXECUTE INSERTAR_CLIENTES ('32094174L','Lucia','Perez','aperez.fr2@gmail.com','Triana',null,'NoUniversitario');
EXECUTE INSERTAR_EMPLEADOS ('32094179L','Sandra','Perez','La vid','sandra@gmail.com',1000,'10-11-2013','10-11-2015',25,'956324264');

--SI SE VA A EJECUTAR MAS DE UNA VEZ SOLO EJECUTAR DE AQUI PARA ABAJO O LOS INSERTARES ANTERIORES DARAN FALLO

SET SERVEROUTPUT ON;
DECLARE
w_IDVENTAS VENTAS.IDVENTAS%TYPE;
w_IDCLIENTE CLIENTES.IDCLIENTE%TYPE;
W_IDEMPLEADO EMPLEADOS.IDEMPLEADO%TYPE;

BEGIN
w_IDEMPLEADO:=sec_EMPLEADOS.currval;
w_IDCLIENTE:=sec_CLIENTES.currval;

PRUEBAS_VENTAS.INICIALIZAR;
PRUEBAS_VENTAS.INSERTAR('Prueba 1','10-11-2013',w_IDEMPLEADO,w_IDCLIENTE,true);
PRUEBAS_VENTAS.INSERTAR('Prueba 2','10-11-2017',w_IDEMPLEADO,w_IDCLIENTE,false);
PRUEBAS_VENTAS.INSERTAR('Prueba 3',SYSDATE,w_IDEMPLEADO,null,true);

w_IDVENTAS:= sec_VENTAS.currval;

PRUEBAS_VENTAS.ACTUALIZAR('Prueba 4',w_IDVENTAS,'11-10-2014',0,w_IDEMPLEADO,null,true);
PRUEBAS_VENTAS.ACTUALIZAR('Prueba 5',w_IDVENTAS,'11-10-2017',0,w_IDEMPLEADO,null,false);
PRUEBAS_VENTAS.ACTUALIZAR('Prueba 6',w_IDVENTAS,'11-10-2014',-1,w_IDEMPLEADO,null,false);
PRUEBAS_VENTAS.ACTUALIZAR('Prueba 7',w_IDVENTAS,'11-10-2014',0,w_IDEMPLEADO,w_IDCLIENTE,true);

PRUEBAS_VENTAS.ELIMINAR('Prueba 8',w_IDVENTAS,true);


END;
