SET SERVEROUTPUT ON;
DECLARE
  IDEMPLEADO NUMBER;
 
BEGIN

PRUEBAS_EMPLEADOS.INICIALIZAR;
PRUEBAS_EMPLEADOS.INSERTAR('PRUEBA 1 - INSERTAR EMPLEADO','49130935L','PEPE','GARCÍA LOPEZ','CALLE BOLIVIA','pepegarlo@gmail.com',1200,SYSDATE,SYSDATE,18,'954723454',TRUE);  
IDEMPLEADO:=SEC_EMPLEADOS.CURRVAL;
PRUEBAS_EMPLEADOS.INSERTAR('PRUEBA 2 - INSERTAR EMPLEADO CON NULOS','47130935L' ,'PEPE','GARCÍA LOPEZ',NULL,'pepegarlo@gmail.com',1200,SYSDATE,NULL,18,'954734589',TRUE);
PRUEBAS_EMPLEADOS.INSERTAR('PRUEBA 3 - INSERTAR EMPLEADO CON NULOS2',NULL,NULL,NULL,'CALLE BOLIVIA',NULL,NULL,NULL,NULL,NULL,NULL,FALSE );
PRUEBAS_EMPLEADOS.INSERTAR('PRUEBA 4 - INSERTAR EMPLEADO MENOR DE 16 AÑOS', '49130965L','PEPE','GARCÍA LOPEZ','CALLE BOLIVIA','pepegarlo@gmail.com',1200,SYSDATE,SYSDATE,15,'954763451', FALSE);
PRUEBAS_EMPLEADOS.INSERTAR('PRUEBA 5 - INSERTAR EMPLEADO CON TELEFONO INCORRECTO', '49180935L','PEPE','GARCÍA LOPEZ','CALLE BOLIVIA','pepegarlo@gmail.com',1200,SYSDATE,SYSDATE,15,'9547345', FALSE);
PRUEBAS_EMPLEADOS.INSERTAR('PRUEBA 6 - INSERTAR EMPLEADO CON DNI INCORRECTO', '4913V','PEPE','GARCÍA LOPEZ','CALLE BOLIVIA','pepegarlo@gmail.com',1200,SYSDATE,SYSDATE,15,'9547345', FALSE);

PRUEBAS_EMPLEADOS.ACTUALIZAR('PRUEBA 7 - ACTUALIZAR EMPLEADO DNI,NOMBRE', IDEMPLEADO, '49130835L','JUAN','GARCÍA LOPEZ','CALLE BOLIVIA','pepegarlo@gmail.com',1200,SYSDATE,SYSDATE,18,'954723454', TRUE);
PRUEBAS_EMPLEADOS.ACTUALIZAR('PRUEBA 8 - ACTUALIZAR EMPLEADO EDAD',IDEMPLEADO , '49134735L','JUAN','GARCÍA LOPEZ','CALLE BOLIVIA','pepegarlo@gmail.com',1200,SYSDATE,SYSDATE,20,'954723454', TRUE);
PRUEBAS_EMPLEADOS.ACTUALIZAR('PRUEBA 9 - ACTUALIZAR EMPLEADO CON NULOS',IDEMPLEADO, null,'PEPE','GARCÍA LOPEZ',NULL,'pepegarlo@gmail.com',1800,SYSDATE,NULL,15,'9547345',FALSE);

PRUEBAS_EMPLEADOS.ELIMINAR('PRUEBA 10 - ELIMINAR EMPLEADO', IDEMPLEADO, TRUE);
END;
