SET SERVEROUTPUT ON;
DECLARE
  IDCLIENTE NUMBER;
  
BEGIN

PRUEBAS_CLIENTES.INICIALIZAR;
PRUEBAS_CLIENTES.INSERTAR('PRUEBA 1 - INSERTAR CLIENTE','49130935L','MARCOS','GARCÍA MORENO','pepegarlo@gmail.com','CALLE BOLIVIA','954723454','Universitario',TRUE);  
IDCLIENTE:=SEC_CLIENTES.CURRVAL;
PRUEBAS_CLIENTES.INSERTAR('PRUEBA 2 - INSERTAR CLIENTE CON NULOS', NULL,NULL,NULL,NULL,'AVENIDA DE ESPAÑA','954723454','Universitario',TRUE);
PRUEBAS_CLIENTES.INSERTAR('PRUEBA 3 - INSERTAR CLIENTE CON TELEFONO INCORRECTO', '49180935L','PEPE','GARCÍA LOPEZ','pepegarlo@gmail.com','CALLE BOLIVIA','95473459899','NoUniversitario', FALSE);
PRUEBAS_CLIENTES.INSERTAR('PRUEBA 4 - INSERTAR CLIENTE CON DNI INCORRECTO', '491378887787878V','TOMÁS','GARCÍA MORENO','tomgarlo@gmail.com','CALLE BOLIVIA','954723454','Universitario', FALSE);

PRUEBAS_CLIENTES.ACTUALIZAR('PRUEBA 5- ACTUALIZAR CLIENTE DNI,NOMBRE', IDCLIENTE,'49130935L','JESUS','GARCÍA MORENO','pepegarlo@gmail.com','CALLE MAR','954723454','Universitario', TRUE);
PRUEBAS_CLIENTES.ACTUALIZAR('PRUEBA 6 - ACTUALIZAR CLIENTE dni incorrecto', IDCLIENTE, '49130935L','MARCOS','GARCÍA MORENO','pepegarlo@gmail.com','CALLE BOLIVIA','92954723454','Universitario', FALSE);
PRUEBAS_CLIENTES.ACTUALIZAR('PRUEBA 7 - ACTUALIZAR CLIENTE CON NULOS',IDCLIENTE,null,null,null,null,'CALLE MAR',null,'Universitario', TRUE);


PRUEBAS_CLIENTES.ELIMINAR('PRUEBA 8 - ELIMINAR CLIENTE', IDCLIENTE, TRUE);
END;
/
