SET SERVEROUTPUT ON;

DECLARE 
  IDCATALOGO NUMBER;
  
    BEGIN
 PRUEBAS_CATALOGO.INICIALIZAR;
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 1 - INSERTAR CATALOGO 1','LAPIZ','UTILIZADO PARA ESCRIBIR',1,'0,18',10,5,'Papeleria','Producto',TRUE);
  IDCATALOGO:= SEC_CATALOGO.CURRVAL;
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 1.2 - INSERTAR CATALOGO 2','BOLIGRAFO',NULL,2,'0,18',15,4,'Papeleria','Producto',TRUE);
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 1.3 - INSERTAR CATALOGO 3','FOTOCOPIA',NULL,1,'0,18',NULL,NULL,'Papeleria','Servicio',TRUE);
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 2 - INSERTAR CATALOGO(NOMBRE NULL)',NULL,'UTILIZADO PARA ESCRIBIR',1,'0,18',10,5,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 3 - INSERTAR CATALOGO(PRECIO NULL)','LAPIZ','UTILIZADO PARA ESCRIBIR',NULL,'0,18',10,5,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 4 - INSERTAR CATALOGO(IVA NULL)','LAPIZ','UTILIZADO PARA ESCRIBIR',1,NULL,10,5,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 5 - INSERTAR CATALOGO(IVA MAYOR QUE 1)','LAPIZ','UTILIZADO PARA ESCRIBIR',1,2,10,5,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 6 - INSERTAR CATALOGO(IVA MENOR QUE 0)','LAPIZ','UTILIZADO PARA ESCRIBIR',1,-2,10,5,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 7 - INSERTAR CATALOGO(PRECIO MENOR QUE 0)','LAPIZ','UTILIZADO PARA ESCRIBIR',-5,'0,18',10,5,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 8 - INSERTAR CATALOGO(TIPO PRODUCTO DISTINTO)','LAPIZ','UTILIZADO PARA ESCRIBIR',1,'0,18',10,5,'COSA','Producto',FALSE);
  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 9 - INSERTAR CATALOGO(TIPO CATALOGO DISTINTO)','LAPIZ','UTILIZADO PARA ESCRIBIR',1,'0,18',10,5,'Papeleria','COSA',FALSE);

  PRUEBAS_CATALOGO.INSERTAR('PRUEBA 10 - INSERTAR CATALOGO(TRIGGER COMPRUEBA STOCK)','LAPICES','UTILIZADO PARA ESCRIBIR',1,'0,18',null,5,'Papeleria','Producto',FALSE);
  
  PRUEBAS_CATALOGO.ACTUALIZAR('PRUEBA 11 - ACTUALIZAR CATALOGO ',IDCATALOGO,'SACAPUNTAS','HERRAMIENTA PARA AFILAR EL LAPIZ',2,'0,28',50,10,'Papeleria','Producto',TRUE);
  PRUEBAS_CATALOGO.ACTUALIZAR('PRUEBA 12 - ACTUALIZAR CATALOGO(NOMBRE NULL) ',IDCATALOGO,NULL,'HERRAMIENTA PARA AFILAR EL LAPIZ',2,'0,28',50,10,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.ACTUALIZAR('PRUEBA 13 - ACTUALIZAR CATALOGO(PRECIO NULL) ',IDCATALOGO,'SACAPUNTAS','HERRAMIENTA PARA AFILAR EL LAPIZ',NULL,'0,28',50,10,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.ACTUALIZAR('PRUEBA 14 - ACTUALIZAR CATALOGO(IVA NULL) ',IDCATALOGO,'SACAPUNTAS','HERRAMIENTA PARA AFILAR EL LAPIZ',2,NULL,50,10,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.ACTUALIZAR('PRUEBA 15 - ACTUALIZAR CATALOGO(IVA MAYOR QUE 1) ',IDCATALOGO,'SACAPUNTAS','HERRAMIENTA PARA AFILAR EL LAPIZ',2,'2,28',50,10,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.ACTUALIZAR('PRUEBA 16 - ACTUALIZAR CATALOGO(IVA MENOR QUE 0) ',IDCATALOGO,'SACAPUNTAS','HERRAMIENTA PARA AFILAR EL LAPIZ',2,'-0,28',50,10,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.ACTUALIZAR('PRUEBA 17 - ACTUALIZAR CATALOGO(PRECIO MENOR QUE 0) ',IDCATALOGO,'SACAPUNTAS','HERRAMIENTA PARA AFILAR EL LAPIZ',-2,'0,28',50,10,'Papeleria','Producto',FALSE);
  PRUEBAS_CATALOGO.ACTUALIZAR('PRUEBA 18 - ACTUALIZAR CATALOGO(TIPO PRODUCTO DISTINTO) ',IDCATALOGO,'SACAPUNTAS','HERRAMIENTA PARA AFILAR EL LAPIZ',2,'0,28',50,10,'Cosa','Producto',FALSE);
  PRUEBAS_CATALOGO.ACTUALIZAR('PRUEBA 19 - ACTUALIZAR CATALOGO(TIPO CATALOGO DISTINTO) ',IDCATALOGO,'SACAPUNTAS','HERRAMIENTA PARA AFILAR EL LAPIZ',2,'0,28',50,10,'Papeleria','Cosa',FALSE);
 
  
  

  PRUEBAS_CATALOGO.ELIMINAR('PRUEBA 20 - ELIMINAR CATALOGO ',IDCATALOGO,TRUE);


  END;
/
