EXECUTE INSERTAR_VENTAS (SYSDATE,2,2) ; --SE SUPONE QUE EXISTE EL EMPLEADO 2 Y EL CLIENTE 2
EXECUTE INSERTAR_CATALOGOS('Boligrafosss','Pinta',3, '0,3',10,7,'Papeleria','Producto');
EXECUTE INSERTAR_CATALOGOS ('Copiasss','Fotocopia','0,1','0,3',null,null,null,'Servicio');
EXECUTE INSERTAR_CATALOGOS('Cartucherasss','guarda cosas',3, '0,3',100,7,'Papeleria','Producto');
--SI SE VA A EJECUTAR MAS DE UNA VEZ EJECUTAR SOLO DE AQUI PARA ABAJO O DARA FALLO AL INSERTAR DOS CATALOGOS CON NOMBRES IGUALES
set serveroutput on;

declare 

w_IDDETALLEVENTA DETALLEVENTA.IDDETALLEVENTA%TYPE;
w_IDVENTA VENTAS.IDVENTAS%TYPE;
w_IDCATALOGO CATALOGO.IDCATALOGO%TYPE;

BEGIN
w_IDVENTA:= sec_VENTAS.currval;
w_IDCATALOGO:= sec_CATALOGO.currval;

PRUEBAS_DETALLEVENTA.INICIALIZAR;
PRUEBAS_DETALLEVENTA.INSERTAR('Prueba 1',20,3,'0,3',w_IDVENTA,w_IDCATALOGO,true);
PRUEBAS_DETALLEVENTA.INSERTAR('Prueba 2',1,3,'0',w_IDVENTA,w_IDCATALOGO,false);
PRUEBAS_DETALLEVENTA.INSERTAR('Prueba 3',15,4,'0,1',w_IDVENTA,w_IDCATALOGO,true);
w_IDDETALLEVENTA := sec_DETALLEVENTA.currval;
PRUEBAS_DETALLEVENTA.ACTUALIZAR ('Prueba 5',w_IDDETALLEVENTA,10,3,'0,05',w_IDCATALOGO,true);
PRUEBAS_DETALLEVENTA.ACTUALIZAR ('Prueba 6',w_IDDETALLEVENTA,-1,8,'0,9',w_IDCATALOGO,false);
PRUEBAS_DETALLEVENTA.ACTUALIZAR ('Prueba 7',w_IDDETALLEVENTA,20,-1,'0,9',w_IDCATALOGO,false);
PRUEBAS_DETALLEVENTA.ACTUALIZAR ('Prueba 8',w_IDDETALLEVENTA,1,2,'1',w_IDCATALOGO,false);
PRUEBAS_DETALLEVENTA.ELIMINAR('Prueba 9', w_IDDETALLEVENTA, true);


END;
