DROP SEQUENCE sec_empleados;
DROP SEQUENCE sec_clientes;
DROP SEQUENCE sec_catalogo;
DROP SEQUENCE sec_ventas;
DROP SEQUENCE sec_proveedor;
DROP SEQUENCE sec_compras;
DROP SEQUENCE sec_detallecompra;
DROP SEQUENCE sec_detalleventa;
DROP SEQUENCE sec_factura;
DROP SEQUENCE sec_ofertas;

CREATE SEQUENCE sec_empleados;
CREATE SEQUENCE sec_clientes;
CREATE SEQUENCE sec_catalogo;
CREATE SEQUENCE sec_ventas;
CREATE SEQUENCE sec_proveedor;
CREATE SEQUENCE sec_compras;
CREATE SEQUENCE sec_detallecompra;
CREATE SEQUENCE sec_detalleventa;
CREATE SEQUENCE sec_factura;
CREATE SEQUENCE sec_ofertas;

CREATE OR REPLACE TRIGGER SEC_EMPLEADOS
BEFORE INSERT ON EMPLEADOS
FOR EACH ROW
BEGIN
IF:NEW.IDEMPLEADO IS NULL THEN SELECT SEC_EMPLEADOS.NEXTVAL INTO :NEW.IDEMPLEADO FROM DUAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER SEC_CLIENTES
BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
IF:NEW.IDCLIENTE IS NULL THEN SELECT SEC_CLIENTES.NEXTVAL INTO :NEW.IDCLIENTE FROM DUAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER SEC_CATALOGOS
BEFORE INSERT ON CATALOGO
FOR EACH ROW
BEGIN
IF:NEW.IDCATALOGO IS NULL THEN SELECT  sec_catalogo.NEXTVAL INTO :NEW.IDCATALOGO FROM DUAL;
END IF;
END;
/
CREATE OR REPLACE TRIGGER SEC_VENTAS
BEFORE INSERT ON VENTAS
FOR EACH ROW
BEGIN
IF:NEW.IDVENTAS IS NULL THEN SELECT SEC_VENTAS.NEXTVAL INTO :NEW.IDVENTAS FROM DUAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER SEC_PROVEEDORES
BEFORE INSERT ON PROVEEDOR
FOR EACH ROW
BEGIN
IF:NEW.IDPROVEEDOR IS NULL THEN SELECT SEC_PROVEEDOR.NEXTVAL INTO :NEW.IDPROVEEDOR FROM DUAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER SEC_COMPRAS
BEFORE INSERT ON COMPRAS
FOR EACH ROW
BEGIN
IF:NEW.IDCOMPRAS IS NULL THEN SELECT SEC_COMPRAS.NEXTVAL INTO :NEW.IDCOMPRAS FROM DUAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER SEC_DETALLECOMPRAS
BEFORE INSERT ON DETALLECOMPRA
FOR EACH ROW
BEGIN
IF:NEW.IDDETALLECOMPRA IS NULL THEN SELECT SEC_DETALLECOMPRA.NEXTVAL INTO :NEW.IDDETALLECOMPRA FROM DUAL;
END IF;
END;
/



CREATE OR REPLACE TRIGGER sec_DETALLEVENTAS
BEFORE INSERT ON DETALLEVENTA
FOR EACH ROW
BEGIN
IF:NEW.IDDETALLEVENTA IS NULL THEN SELECT sec_detalleventa.NEXTVAL INTO:NEW.IDDETALLEVENTA FROM DUAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER SEC_FACTURA
BEFORE INSERT ON FACTURA
FOR EACH ROW
BEGIN
IF:NEW.IDFACTURA IS NULL THEN SELECT sec_factura.NEXTVAL INTO :NEW.IDFACTURA FROM DUAL;
END IF;
END;
/

CREATE OR REPLACE TRIGGER SEC_OFERTAS
BEFORE INSERT ON OFERTAS
FOR EACH ROW
BEGIN
IF:NEW.IDOFERTA IS NULL THEN SELECT SEC_OFERTAS.NEXTVAL INTO :NEW.IDOFERTA FROM DUAL;
END IF;
END;
/
